### ISSUE TITLE
`rsvp help` should be a private response

### ISSUE THREAD

**Issue by wtfcarlos** [kokeshii/RSVPBot#38]
@ifo already implemented this feature, and it worked, but for some reason it got broken and we're not sure why.

**Comment by wtfcarlos** [comment]
As an extra data point, IIRC, the PR that @pnasrat made with regards to supporting multiple responses for a single command was around the time it broke.

**Comment by alexandrinaw** [comment]
[Here's the start of a PR that'll fix it](https://github.com/kokeshii/RSVPBot/compare/dev...alexandrinaw:rsvp_help_reply_privately). I verified that it works locally but I'm not in the mood to write tests right now...haha.
