### ISSUE TITLE
parse dates more flexibly

### ISSUE THREAD

**Issue by jameysharp** [kokeshii/RSVPBot#43]
It'd be great if RSVPBot would use something like [dateparser](https://github.com/scrapinghub/dateparser) to accept dates in a variety of formats.

I think if you use `settings={'PREFER_DATES_FROM': 'future'}`, it'll even do the right thing if someone just sets the date to a string like "Tuesday".

Also maybe you can allow the time to be optionally set in the same command as the date, this way. I'm hoping input like "Tuesday at 2pm" works, but I haven't tested it.

**Comment by jjst** [comment]
I'm still working on an issue related to how the `dateparser` library handles timezones, which results in weird behaviour. Stay tuned for a follow-up PR.
