### ISSUE TITLE
Doesn't work in opt-in streams

### ISSUE THREAD

**Issue by strugee** [kokeshii/RSVPBot#73]
Someone recently made an event in the `politics` stream, which is opt-in. RSVPbot doesn't seem to have picked this up - there should be some way to ask RSVPbot to join another stream. Or maybe it should just subscribe to everything.

**Comment by qwo** [comment]
@strugee I would normal streams. I think the bot is just not working?

**Comment by strugee** [comment]
Yeah, according to Christopher Edgemon that might be it. I'll close if that's the case.
