### ISSUE TITLE
iCal feed of events you've RSVP'd to

### ISSUE THREAD

**Issue by zachallaun** [kokeshii/RSVPBot#78]
Originally opened by @strugee https://github.com/kokeshii/RSVPBot/issues/72:

> It would be sick if RSVPbot was able to give me an iCal feed I could plug into my calendar so stuff automatically shows up when I rsvp yes.

**Comment by zachallaun** [comment]
@strugee This is now possible with the new RSVPBot! Since `rsvp yes` is actually signing you up for the event on the RC calendar, you can use the iCal export link [in the bottom right](https://www.recurse.com/calendar) to add all the events you're going to. (In the future you'll likely be able to export arbitrary searches/views of RC events, but for now you can just do it with events you're going to.)

**Comment by strugee** [comment]
:tada: thank you!
